Controllers/BusController.cs
using CompanyMvc.Data;
using CompanyMvc.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CompanyMvc.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BusController : Controller
    {
        private readonly ApplicationDbContext _dBcontext;
        public BusController(ApplicationDbContext dBcontext)
        {
            _dBcontext = dBcontext;
        }

        public async Task<ActionResult<BusModel>> Index()
        {
            var buses = await _dBcontext.Buses.Join(_dBcontext.BusRoutes, b => b.BusId, r => r.BusId, (b, r) => new BusModel
            {
                BusId = b.BusId,
                BusNo = b.BusNo,
                Capacity = b.Capacity,
                Source = r.Source,
                Destination = r.Destination,
                RouteTag = r.RouteTag,
                SeatsAvailable = b.SeatsAvailable,
                DateAvailable = b.DateAvailable,
                DepartureTime = b.DepartureTime
            }).ToListAsync();
            return View(buses);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult<Bus>> Create(Bus bus)
        {
            if (ModelState.IsValid)
            {
                _dBcontext.Buses.Add(bus);
                await _dBcontext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var bus = await _dBcontext.Buses.FindAsync(id);
            return View(bus);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Bus bus)
        {
            var bustoUpdate = await _dBcontext.Buses.FindAsync(bus.BusId);
            if (bustoUpdate == null)
            {
                return RedirectToAction(nameof(Index));
            }
            bustoUpdate.BusNo = bus.BusNo;
            bustoUpdate.BusRoute = bus.BusRoute;
            bustoUpdate.Capacity = bus.Capacity;
            bustoUpdate.SeatsAvailable = bus.SeatsAvailable;
            bustoUpdate.Type = bus.Type;
            await _dBcontext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/UserController.cs
using CompanyMvc.Models;
using CompanyMvc.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CompanyMvc.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signManager;

        public UserController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signManager)
        {
            _userManager = userManager;
            _signManager = signManager;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegistrationViewModel registration)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser()
                {
                    Email = registration.Email,
                    UserName = registration.FirstName,
                    PhoneNumber = registration.PhoneNumber,
                    NationalId = registration.NationalId,
                    FirstName = registration.FirstName,
                    LastName = registration.LastName
                };
                var result = await _userManager.CreateAsync(user, registration.Password);
                if (result.Succeeded)
                {
                    await _signManager.SignInAsync(user, false);
                    return RedirectToAction(nameof(Index), "Home");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel loginViewModel)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser();
                user = await _userManager.FindByEmailAsync(loginViewModel.Email);
                var result = await _signManager.PasswordSignInAsync(user.UserName, loginViewModel.Password, loginViewModel.Remember, false);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index), "Home");
                }
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _signManager.SignOutAsync();
            return RedirectToAction(nameof(Index), "home");
        }

    }
}

Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> _signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Airdrive</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CompanyMvc.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/20.3.47/material.css" />
    <script src="https://cdn.syncfusion.com/ej2/20.3.47/dist/ej2.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CompanyMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (_signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                @* <i class="fa-solid fa-user 2xl"></i> *@
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">My Account</a>
                            </li>
                            <li class="nav-item">
                                @* <i class="fa-regular fa-right-from-bracket fa-2xl"></i> *@
                                <form asp-action="Logout" asp-controller="User" method="post">
                                    <button type="submit" class="btn btn-link nav-link py-0" style="width: auto;">LogOut @User.Identity.Name</button>
                                </form>
                            </li>
                            @* <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bus" asp-action="Index">View Buses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bus" asp-action="Create">Add Buses</a>
                            </li> *@
                        }else
                        {
                            <li class="nav-item">
                                @* <i class="fa-regular fa-right-to-bracket"></i> *@
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                @* <i class="fa-sharp fa-solid fa-arrow-right-to-arc fa-2xl"></i> *@
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-1">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Airdrive - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://kit.fontawesome.com/c03a81ce8e.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <ejs-scripts></ejs-scripts>
    @Html.EJS().ScriptManager()
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>